### ISSUE TITLE
Support the other command-line utils

### ISSUE THREAD

**Issue by cbm755** [flathub/org.plomgrading.PlomClient#23]
What other deps are needed to support `plom-build`, `plom-scan` etc etc from here?  pandas at least [1].  Maybe imagemagick?  Probably pymupdf for `plom-finish`...   TODO: needs decision upstream [2].

[1] https://gitlab.com/plom/plom/-/merge_requests/1012#note_663433476
[2] TODO: Plom issue number here!

CC @njhlai, hopefully same person on GitHub as GitLab, apologies for random spam if not!

**Comment by njhlai** [comment]
Yeap, you got the right person! I can dig into this a little, though it may take awhile.

**Comment by cbm755** [comment]
nah, those are only for legacy servers now, likely not needed.
