### ISSUE TITLE
Legacy windowing system: unsafe

### ISSUE THREAD

**Issue by cbm755** [flathub/org.plomgrading.PlomClient#32]
Gnome Software shows us like this:

![Screenshot from 2021-11-05 09-23-13](https://user-images.githubusercontent.com/818622/140544387-aece71bd-6302-4e14-ac08-e9f978326fc3.png)

Might be nice to not have that red warning.  Is this b/c of #16?

**Comment by PitamahBhishma-0** [comment]
can any one explain why is this showing ?

**Comment by bilelmoussaoui** [comment]
because the app is using socket=x11 instead of socket=fallback-x11, which means the app always gets access to the x11 socket instead of being a fallback of the wayland one.

**Comment by cbm755** [comment]
Thank you both, I will try `socket=fallback-x11` on the next minor version bump

**Comment by cbm755** [comment]
I tried it in cc25547825efd2587e7b9ef4eaa46ea1e30bb425, but now I get:
```
flatpak run org.plomgrading.PlomClient 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

**Comment by cbm755** [comment]
TODO: check this in a couple days now that #16 is fixed

**Comment by cbm755** [comment]
Better:

![image](https://github.com/flathub/org.plomgrading.PlomClient/assets/818622/a28f4460-c812-46d1-a3c5-76e480fd7d14)

No more mention of unsafe windowing.
